version: 2

defaults: &defaults
  working_directory: ~/project/react-stick
  docker:
    - image: circleci/node:latest-browsers
      environment:
        CHROME_BIN: "/usr/bin/google-chrome"

attach_workspace: &attach_workspace
  attach_workspace:
    at: ~/project

restore_cache: &restore_cache
  restore_cache:
    name: Restore node_modules cache
    keys:
      - v1-node-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - v1-node-{{ .Branch }}-
      - v1-node-

jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - *attach_workspace
      - *restore_cache
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save yarn cache
          key: v1-yarn-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - .cache/yarn
      - save_cache:
          name: Save node_modules cache
          key: v1-node-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules/
      - run:
          name: Remove node_modules to cleanup workspace
          command: rm -r node_modules/
      - persist_to_workspace:
          root: ~/project
          paths:
            - react-stick

  lint:
    <<: *defaults
    steps:
      - *attach_workspace
      - *restore_cache
      - run:
          name: Lint
          command: yarn lint

  flow:
    <<: *defaults
    steps:
      - *attach_workspace
      - *restore_cache
      - run:
          name: Flow
          command: yarn flow

  test:
    <<: *defaults
    steps:
      - *attach_workspace
      - *restore_cache
      - run:
          name: Test
          command: yarn test:coverage
      - run:
          name: Codecov
          command: bash <(curl -s https://codecov.io/bash)

  publish-demo:
    <<: *defaults
    steps:
      - *attach_workspace
      - *restore_cache
      - run:
          name: Fix host authenticity for github.com
          command: mkdir -p ~/.ssh/ && ssh-keyscan github.com >> ~/.ssh/known_hosts
      - run:
          name: Set git name & email
          command: |
            git config --global user.name "Workflow Bot" && git config --global user.email "dev@effektif.com"
      - run:
          name: Build demo
          command: yarn build-demo
      - run:
          name: Publish demo
          command: yarn publish-demo

  release-preview:
    <<: *defaults
    steps:
      - *attach_workspace
      - *restore_cache
      - run:
          name: Post release preview
          command: "[[ $CI_PULL_REQUEST != '' ]] && yarn semantic-release-preview || exit 0"

  release:
    <<: *defaults
    steps:
      - *attach_workspace
      - *restore_cache
      - run:
          name: Build
          command: yarn build
      - run:
          name: Release
          command: yarn semantic-release

workflows:
  version: 2
  qa-publish-release:
    jobs:
      - install
      - lint:
          requires:
            - install
      - flow:
          requires:
            - install
      - test:
          requires:
            - install
      - publish-demo:
          requires:
            - install
      - release-preview:
          requires:
            - lint
            - flow
            - test
          filters:
            branches:
              ignore: master
      - release:
          context: NPM
          requires:
            - lint
            - flow
            - test
          filters:
            branches:
              only: master
