version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.3.0

references:
  defaults: &defaults
    working_directory: ~/repo
    docker:
      - image: cimg/node:16.15-browsers
        environment:
          CHROME_BIN: '/usr/bin/google-chrome'

  restore_cache: &restore_cache
    restore_cache:
      keys:
        - deps-v4-{{ .Branch }}-{{ checksum "package-lock.json" }}
        - deps-v4-{{ .Branch }}
        - deps-v4

jobs:
  install:
    <<: *defaults

    steps:
      - checkout

      - *restore_cache

      - run: npm ci

      - save_cache:
          key: deps-v4-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - node_modules

  lint:
    <<: *defaults

    steps:
      - checkout

      - *restore_cache

      - run:
          name: Lint
          command: npm run lint

  flow:
    <<: *defaults

    steps:
      - checkout

      - *restore_cache

      - run:
          name: Flow
          command: npm run flow

  test:
    <<: *defaults
    steps:
      - checkout

      - *restore_cache

      - browser-tools/install-chrome

      - run:
          name: Test
          command: npm run test --coverage

      - run:
          name: Codecov
          command: bash <(curl -s https://codecov.io/bash)

  release:
    <<: *defaults
    steps:
      - checkout
      - *restore_cache
      - run:
          name: Fix host authenticity for github.com
          command: mkdir -p ~/.ssh/ && ssh-keyscan github.com >> ~/.ssh/known_hosts
      - run:
          name: Build
          command: npm run build
      - run:
          name: Release
          command: npm run semantic-release

workflows:
  version: 2
  qa-publish-release:
    jobs:
      - install
      - lint:
          requires:
            - install
      - flow:
          requires:
            - install
      - test:
          requires:
            - install
          filters:
            branches:
              ignore: master
      - release:
          context: NPM
          requires:
            - install
          filters:
            branches:
              only: master
